create table Addproperty14(
id int identity primary key,
propertyname varchar(200),
minimumprice varchar (200),
maximumprice varchar (200),
uploadphoto varchar (200),
facebookurl varchar (200),
instargramurl varchar (200),
Whatsappno varchar (200),
youtubeviewurl varchar (200),
AreainSqft varchar (200),
noofbedroom varchar (200),
noofbathroom varchar (200),
Garage varchar (200),
ListPropertyFor varchar (200),
Ihavea varchar (200),
PropertyType varchar (200),
AvailableFor varchar (200),
GoogleMapUrl text,
ShortDiscription text,
LongDescription text,
NearByPlaces text,
Landmark varchar (200),
City varchar (200),
Pincode varchar (200),
FullAddress varchar (200),
slug varchar (200),
);

select * from  Addproperty14;
